print("Tell me an adjective, and click enter. ")
adjective1 = input()
print("Tell me a noun (plural), and click enter. ")
noun1 = input()
print("Tell me another noun, and click enter. ")
noun2 = input()
print("Tell me an another adjective, and click enter. ")
adjective2 = input()

print ("Octopi are " + adjective1)
print (noun1 + " are uneducated swine")
print ("The " + noun2 + " is circular and " + adjective2)
print ("And so are you!")
